/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.beans.PropertyVetoException;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author Tiago B
 */
public class FrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrPrincipal
     */
    public FrPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        jMenuItem1.setText("Novo Frame");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Novo");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //Adicionando frame interno.
        Frame f = new JFrame("frame"); 
                
        contador = contador+1;
  
        // set layout of frame 
        setLayout(null);
        // create a internal frame 
        internal = new JInternalFrame("Banco "+String.valueOf(contador), true, false, true, true); 
        try {
            internal.setClosed(true);
            internal.setSize(400, 800);
            internal.setBounds(100, 0, 0, 0);
            internal.setResizable(false);
            internal.setClosable(true);
            internal.setMaximizable(false);
            internal.setSelected(true);
            //Determina a dimensão do frame interno.
            internal.setPreferredSize(new java.awt.Dimension(300,200));
        } catch (PropertyVetoException ex) {
            Logger.getLogger(FrPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /*
        *********Criar componentes***********
        */
        JPanel painel = new JPanel(); 
        painel.setLayout(null);
        painel.setSize(600, 400);
        
        //Toogle button
        JToggleButton toogleConectado = new JToggleButton("Conectado");
        toogleConectado.setBounds(70, 10, 150, 50);    
        
        
        //Label
        JLabel label = new JLabel("Status"); 
        label.setText("Status");
        label.setBounds(70, 50, 200, 50);
        
        // create a Button 
        JButton button = new JButton("button");     
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(rootPane, "Teste : "+internal.getTitle());
                if(toogleConectado.getText().equals("Conectado")){
                    toogleConectado.setText("Não conectado");
                }
                else{
                    if(toogleConectado.getText().equals("Não conectado"))
                    {
                        toogleConectado.setText("Conectado");
                    }
                }
                
                TimerTask repeatedTask = new TimerTask() 
                {
                    @Override
                    public void run() {
                        label.setText("Hora : "+new Date());
                    }
                };
                Timer timer = new Timer("Timer");
     
                long delay  = 1000L;
                long period = 1000L;
                timer.scheduleAtFixedRate(repeatedTask, delay, period);
                
            }
        });
        button.setBounds(10, 125, 270, 40);
        
        // create a label to display text 
        
        
        /*
        ***Adicionar componentes no panel*****
        */
        
        // add label and button to panel 
        painel.add(label);         
        painel.add(button); 
        painel.add(toogleConectado);
       
        // add panel to internal frame 
        internal.add(painel); 
        
        //Initial position of frame in screen.
        internal.setBounds(500, 200, 300, 200);
        // set visibility internal frame 
        internal.setVisible(true);         
        
        // add internal frame to frame      
        add(internal);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     /*   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPrincipal().setVisible(true);
            }
        });
    }*/
    public JInternalFrame internal;
    int contador = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
